const data = [
	"What is your name?",
	"Your nickname",
	"Your phone number",
	"Where do you stay?",
	"When did you cry for the first time?",
	"What is your favourite colour?",
	"My Name in your phone",
	"What is your favourite cuisine?",
	"Any Name, you would like to call me?",
	"Movies that you can watch for a lifetime",
	"What is your favourite memory of us?",
	"What kind of dresses do you like to wear?",
	"Describe in one word, Friendship is",
	"Describe your soul mate",
	"Do you believe in love? Why or why not?",
	"Who is/was your celebrity crush on a TV character when you were a teenager?",
	"Favorite Vacation Spots and your dream destination",
	"Your crush in real life",
	"If you are given another chance to live your life. What are the 3 things will you do or like to change?",
	"Who is your role model/heart throb?",
	"Funniest thing that has happened to you?",
	"Which colour suits me the best?",
	"I am your?",
	"Dedicate a song for me",
	"Message for me",
]
